import {Viewer} from './viewer.js';
import {schemaForm} from './api-form.js';
import {installBodyPanel} from './body-panel.js';

const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={assets:{characters:[],clips:[]},character:null,clip:null,species:'human',action:'walk',playing:true,frame:0,time:0,busy:false,tools:[],capabilities:null};
let toolForm,toolFormSequence=0,toolFormContext={};
let viewer;try{viewer=new Viewer($('#viewport'));}catch(e){$('#render-error').hidden=false;$('#render-error').textContent='The 3D preview needs WebGL. Enable hardware acceleration or use another browser. Motion tools and exports remain available.';}
let toastTimer;
function toast(message,error=false){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').classList.toggle('error',error);$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,error?9000:4000);}
async function request(path,body){const options=body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{};const r=await fetch(path,options);const data=await r.json();if(!r.ok)throw Error(data.error||'Request failed');return data;}
function call(name,args={}){return request('/api/call',{name,arguments:args});}
function busy(value){state.busy=value;['generate','simulate','create-rig','run-tool'].forEach(id=>$('#'+id).disabled=value||(id==='simulate'&&(!state.capabilities?.backends.mujoco||state.character?.joint_limits_calibrated===false)));$('#generate').innerHTML=value?'Generating…':'<span class="spark">✳</span> Generate motion <span>↗</span>';}
async function task(fn){if(state.busy)return;busy(true);try{await fn();}catch(e){toast(e.message,true);}finally{busy(false);}}
const labels={idle:'Idle',walk:'Walk',run:'Run',jump:'Jump',squat:'Squat',wave:'Wave',trot:'Trot',serve:'Serve · authored',recorded_serve:'Serve · recorded',zverev_reference_serve:'Serve · Zverev',reference_serve:'Serve · reference',passive_dynamics:'Passive dynamics',pose:'Authored pose',body_motion:'Body motion'};
function fillMotions(){const actions=[...state.capabilities.species[state.species],...(state.species==='human'?['recorded_serve','zverev_reference_serve']:[])];$('#motion-grid').replaceChildren();actions.forEach(action=>{const b=document.createElement('button');b.className='motion-card'+(state.action===action?' active':'');b.textContent=labels[action];b.onclick=()=>{state.action=action;fillMotions();};$('#motion-grid').append(b);});$$('.jump-control').forEach(el=>el.hidden=state.action!=='jump');const locomotion=['walk','run','trot'].includes(state.action);$('#speed').disabled=!locomotion;$('#stride').disabled=!locomotion;$('#duration').disabled=['recorded_serve','zverev_reference_serve'].includes(state.action);}
function useCharacter(char){state.character=char;$('#simulate').disabled=state.busy||!state.capabilities?.backends.mujoco||char.joint_limits_calibrated===false;$('#physics-status').textContent=char.joint_limits_calibrated===false?'Passive dynamics is unavailable for this coordinate profile.':state.capabilities?.backends.mujoco?'MuJoCo ready · 240 Hz simulation':'Install physics extras to enable MuJoCo.';state.species=char.species;$('#height').value=char.height;$('#mass').value=char.mass;$('#height-label').textContent=char.species==='dog'?'Withers scale · m':'Height · m';$('#joint-count').textContent=char.joints.length+' joints';$$('[data-species]').forEach(b=>b.classList.toggle('active',b.dataset.species===char.species));if(!state.capabilities.species[state.species].includes(state.action))state.action='walk';fillCharacters();fillMotions();}
function fillCharacters(){const select=$('#character-select');select.replaceChildren();state.assets.characters.filter(c=>c.species===state.species).forEach(c=>{const o=document.createElement('option');o.value=c.id;o.textContent=c.name+' · '+c.height.toFixed(2)+' m';select.append(o);});if(state.character)select.value=state.character.id;}
function fillTakes(){const list=$('#clip-list');list.replaceChildren();$('#take-count').textContent=state.assets.clips.length;state.assets.clips.slice(0,8).forEach(c=>{const b=document.createElement('button');b.className='take'+(state.clip?.id===c.id?' active':'');const symbol=document.createElement('span');symbol.className='take-symbol';symbol.textContent='◈';const text=document.createElement('span');text.className='take-text';text.textContent=labels[c.action]||c.action;const sub=document.createElement('small');sub.textContent=c.character;const duration=document.createElement('small');duration.textContent=c.duration.toFixed(1)+' s';text.append(sub);b.append(symbol,text,duration);b.onclick=()=>task(()=>loadClip(c.id));list.append(b);});}
async function refresh(){state.assets=await request('/api/assets');fillCharacters();fillTakes();}
async function loadClip(id){
  const clip=await request('/api/clips/'+id);state.clip=clip;state.time=0;state.frame=0;
  const character=state.assets.characters.find(c=>c.id===clip.rig.id);if(character)useCharacter(character);
  state.action=clip.action;fillMotions();$('#joint-count').textContent=clip.rig.joints.length+' joints';viewer?.load(clip);state.playing=true;$('#play').textContent='Ⅱ';$('#play').setAttribute('aria-label','Pause');
  $('#clip-title').textContent=(clip.rig.species==='human'?'Human':'Canine')+' '+(labels[clip.action]||clip.action).toLowerCase();
  $('#backend-label').textContent=clip.backend.startsWith('mujoco')?'MUJOCO · PASSIVE DYNAMICS':clip.backend==='authored_pose'?'AUTHORED POSE':clip.backend==='video_guided_reconstruction'?'VIDEO REFERENCE · DEPTH ESTIMATED':clip.backend==='motion_capture'?'MOTION CAPTURE · BALL RECONSTRUCTED':clip.backend==='constrained_kinematic'?'CONSTRAINED REFERENCE':clip.backend==='coupled_kinematic'?'COUPLED BODY · SYNTHETIC PROFILE':'PROCEDURAL REFERENCE';
  $('#scrubber').max=clip.frames.length-1;$('#time-total').textContent=timecode(clip.duration);$('#sample-rate').textContent=clip.fps+' FPS';
  const requestedDuration=clip.timing?.requested_duration??clip.duration;$('#duration').value=requestedDuration;$('#duration-value').textContent=requestedDuration.toFixed(1)+' s';
  if(clip.parameters.speed>0){$('#speed').value=clip.parameters.speed;$('#speed-value').textContent=clip.parameters.speed.toFixed(1)+' m/s';}
  if(clip.parameters.stride_scale){$('#stride').value=clip.parameters.stride_scale;$('#stride-value').textContent=clip.parameters.stride_scale.toFixed(2)+'×';}
  if(clip.parameters.jump_height){$('#jump-height').value=clip.parameters.jump_height;$('#jump-height-value').textContent=clip.parameters.jump_height.toFixed(2)+' m';}
  drawMetrics(clip.evaluation);drawTracks(clip);fillTakes();updateFrame();
}
function drawMetrics(report){
  const m=report.metrics;const good=report.status==='checks_passed';$('#check-status').classList.toggle('warn',!good);$('#check-status').textContent=good?'✓  Geometric checks passed':'△  Motion needs review';
  const metrics=[['Bone length error',(m.max_bone_length_error_m*1000).toFixed(3),'mm'],['Ground penetration',(m.max_ground_penetration_m*1000).toFixed(2),'mm'],['Foot slip · p95',m.stance_foot_slip_p95_m_s===null?'—':(m.stance_foot_slip_p95_m_s*100).toFixed(2),'cm/s'],['Joint limits',report.checks.joint_limits===null?'Not calibrated':m.joint_limit_violations_sample.length===0?'Within range':m.joint_limit_violations_sample.length+'+ violations',''],['Root jerk · RMS',m.root_jerk_rms_m_s3?.toFixed(1)||'—','m/s³']];
  if(report.checks.coupled_body_limits!==undefined){metrics.push(['Coupled body limits',report.checks.coupled_body_limits?'Within envelope':'Blocked',''],['Limb clearance',(m.minimum_limb_clearance_m*1000).toFixed(1),'mm'],['Temporal budgets',report.checks.temporal_budgets?'Within budget':'Exceeded','']);}
  if(state.clip?.timing){const t=state.clip.timing;metrics.push(['Requested → actual time',t.requested_duration.toFixed(2)+' → '+t.actual_duration.toFixed(2),'s']);}
  if(state.clip?.attachments?.length){metrics.push(['Grip drift',(m.max_grip_position_error_m*1000).toFixed(3),'mm'],['Grip rotation drift',m.max_grip_rotation_error_deg.toFixed(3),'°']);}
  if(state.clip?.pose_pins?.length)metrics.push(['Contact pose error',m.max_pinned_pose_error_deg.toFixed(3),'°']);$('#metrics').replaceChildren();for(const [label,value,unit]of metrics){const row=document.createElement('div');row.className='metric';const l=document.createElement('span');l.textContent=label;const v=document.createElement('strong');v.textContent=value+' ';const u=document.createElement('small');u.textContent=unit;v.append(u);row.append(l,v);$('#metrics').append(row);}
}
function drawTracks(clip){
  $('#timeline-ticks').replaceChildren();for(let i=0;i<5;i++){const span=document.createElement('span');span.textContent=(clip.duration*i/4).toFixed(1)+'s';$('#timeline-ticks').append(span);}
  const tracks=$('#contact-tracks');tracks.replaceChildren();const names=Object.keys(clip.frames[0].contacts);
  for(const name of names){const row=document.createElement('div');row.className='track';const label=document.createElement('span');label.className='track-name';label.textContent=name.replace('_toe','').replace('left','L').replace('right','R').replace('_',' ');const lane=document.createElement('div');lane.className='track-lane';let start=null;const frames=clip.frames;
    for(let i=0;i<=frames.length;i++){const active=i<frames.length&&frames[i].contacts[name];if(active&&start===null)start=i;if(!active&&start!==null){const block=document.createElement('i');block.className='track-segment';block.style.left=(start/frames.length*100)+'%';block.style.width=((i-start)/frames.length*100)+'%';lane.append(block);start=null;}}
    row.append(label,lane);tracks.append(row);
  }
}
function timecode(t){return '00:'+Math.floor(t).toString().padStart(2,'0')+'.'+Math.floor(t%1*100).toString().padStart(2,'0');}
function updateFrame(){if(!state.clip)return;state.frame=Math.min(state.clip.frames.length-1,Math.floor(state.time*state.clip.fps+1e-6));viewer?.draw(state.time*state.clip.fps);$('#time-current').textContent=timecode(state.time);$('#scrubber').value=state.frame;$('#frame-label').textContent='FRAME '+state.frame.toString().padStart(4,'0')+' / '+(state.clip.frames.length-1).toString().padStart(4,'0');}
$('#generate').onclick=()=>task(async()=>{if(state.action==='zverev_reference_serve'){const result=await call('create_animation',{recipe:'zverev_serve'});await refresh();await loadClip(result.clip_id);toast('Zverev reference recipe reconstructed and checked');return;}if(state.action==='recorded_serve'){const result=await call('load_recording',{character_id:state.character.id,recording:'tennis_serve',fps:60});await refresh();await loadClip(result.id);toast('Recorded body and racket motion loaded');return;}if(!state.capabilities.species[state.species].includes(state.action)){state.action='walk';fillMotions();}const result=await call('generate_motion',{character_id:state.character.id,action:state.action,speed:+$('#speed').value,duration:+$('#duration').value,stride_scale:+$('#stride').value,jump_height:+$('#jump-height').value,fps:60});await refresh();await loadClip(result.id);toast('Motion generated · '+result.frame_count+' frames');});
$('#simulate').onclick=()=>task(async()=>{const r=await call('simulate_physics',{character_id:state.character.id,duration:3,fps:60});await refresh();await loadClip(r.id);toast('Passive dynamics complete. No balance control is applied.');});
$('#create-rig').onclick=()=>task(async()=>{const r=await call('create_character',{species:state.species,name:(state.species==='human'?'Human':'Canine')+' '+String(state.assets.characters.length+1).padStart(2,'0'),height:+$('#height').value,mass:+$('#mass').value});await refresh();useCharacter(r);const clip=await call('generate_motion',{character_id:r.id,action:'idle',duration:4});await refresh();await loadClip(clip.id);toast('Character created');});
$$('[data-species]').forEach(b=>b.onclick=()=>task(async()=>{const char=state.assets.characters.find(c=>c.species===b.dataset.species);if(char){useCharacter(char);const take=state.assets.clips.find(c=>c.character_id===char.id);if(take)await loadClip(take.id);}}));
$('#character-select').onchange=()=>task(async()=>{const c=state.assets.characters.find(c=>c.id===$('#character-select').value);if(c){useCharacter(c);const take=state.assets.clips.find(t=>t.character_id===c.id);if(take)await loadClip(take.id);else{const clip=await call('generate_motion',{character_id:c.id,action:'idle',duration:4});await refresh();await loadClip(clip.id);}}});
for(const [id,suffix,digits]of [['speed',' m/s',1],['duration',' s',1],['stride','×',2],['jump-height',' m',2]])$('#'+id).oninput=()=>$('#'+id+'-value').textContent=(+$('#'+id).value).toFixed(digits)+suffix;
$('#play').onclick=()=>{if(state.clip&&state.time>=state.clip.duration)state.time=0;state.playing=!state.playing;$('#play').textContent=state.playing?'Ⅱ':'▶';$('#play').setAttribute('aria-label',state.playing?'Pause':'Play');};
$('#restart').onclick=()=>{state.time=0;updateFrame();};$('#scrubber').oninput=()=>{state.playing=false;$('#play').textContent='▶';$('#play').setAttribute('aria-label','Play');state.time=+$('#scrubber').value/(state.clip?.fps||60);updateFrame();};
$('#camera-view').onchange=()=>viewer?.setView($('#camera-view').value);$('#reset-view').onclick=()=>viewer?.setView($('#camera-view').value);
$('#solid-view').onclick=()=>{if(viewer)viewer.solid=true;$('#solid-view').classList.add('active');$('#skeleton-view').classList.remove('active');updateFrame();};
$('#skeleton-view').onclick=()=>{if(viewer)viewer.solid=false;$('#solid-view').classList.remove('active');$('#skeleton-view').classList.add('active');updateFrame();};
$('#show-grid').onchange=()=>{if(viewer)viewer.grid.visible=$('#show-grid').checked;};$('#show-contacts').onchange=()=>{if(viewer)viewer.showContacts=$('#show-contacts').checked;updateFrame();};$('#show-com').onchange=()=>{if(viewer)viewer.showCom=$('#show-com').checked;updateFrame();};
$('#follow-camera').onclick=()=>{if(!viewer)return;viewer.follow=!viewer.follow;$('#follow-camera').setAttribute('aria-pressed',String(viewer.follow));$('#follow-camera').querySelector('span').textContent=viewer.follow?'●':'○';};
$('#refresh').onclick=()=>task(async()=>{await refresh();toast('Saved characters and takes refreshed');});
$$('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));
$('#export-open').onclick=()=>state.clip&&$('#export-dialog').showModal();$$('[data-format]').forEach(b=>b.onclick=()=>task(async()=>{if(!state.clip)return;if(b.dataset.format==='mp4'){const result=await call('finish_animation',{clip_id:state.clip.id,formats:['mp4']});const file=result.files.find(f=>f.format==='mp4');if(file.status!=='ready')throw Error(file.reason||file.install||'Video renderer is unavailable');}const a=document.createElement('a');a.href='/api/export/'+state.clip.id+'.'+b.dataset.format;a.download='anima-'+state.clip.action+'.'+b.dataset.format;a.click();$('#export-dialog').close();}));
$('#open-tools').onclick=()=>{$('#tools-dialog').showModal();toolSelected();};$('#studio-tab').onclick=()=>$$('dialog').forEach(d=>d.close());
function toolArgs(name){const character_id=state.character?.id,clip_id=state.clip?.id;return {list_motion_recipes:{query:'Zverev'},create_animation:{recipe:'zverev_serve'},inspect_animation:{clip_id},revise_animation:{clip_id,tempo:1},finish_animation:{clip_id,formats:['mp4'],quality:'final'},import_reference_motion:{manifest_file:'reference.json'},create_character:{species:'human',name:'Human 02',height:1.8,mass:78},get_character:{character_id},load_recording:{character_id,recording:'tennis_serve',fps:60},generate_motion:{character_id,action:state.species==='dog'?'trot':'walk',duration:4,speed:1.2,fps:60},define_pose:{character_id,joint_angles:{},duration:1},get_clip:{clip_id,frame_start:0,frame_count:1},evaluate_motion:{clip_id},export_motion:{clip_id,format:'bvh'},describe_body_controls:{character_id},configure_body:{character_id,settings:{}},preview_body_pose:{character_id,coordinates:{right_arm_elevation:150,right_arm_plane:65}},animate_body:{character_id,keyframes:[{time:0,coordinates:{}},{time:2,coordinates:{right_arm_elevation:140,right_arm_plane:65}}]},simulate_physics:{character_id,duration:2},solve_ik:{root:[0,1,0],target:[0,.25,.3],pole:[0,1,1],upper_length:.43,lower_length:.43}}[name]||{};}
function toolSelected(){const tool=state.tools.find(t=>t.name===$('#tool-select').value);if(!tool)return;$('#tool-description').textContent=tool.description;$('#tool-schema').textContent=JSON.stringify(tool.inputSchema,null,2);$('#tool-args').value=JSON.stringify(toolArgs(tool.name),null,2);buildToolForm(tool);}
$('#tool-select').onchange=toolSelected;$('#run-tool').onclick=()=>task(async()=>{try{const r=await call($('#tool-select').value,$('#tool-json-mode').checked?JSON.parse($('#tool-args').value):toolForm.value());$('#tool-result').textContent=JSON.stringify(r,null,2);await refresh();if(r.id?.startsWith('clip_'))await loadClip(r.id);if(r.clip_id)await loadClip(r.clip_id);if(r.id?.startsWith('character_'))useCharacter(r);}catch(e){$('#tool-result').textContent='Error: '+e.message;throw e;}});
$('#connect-llm').onclick=()=>task(async()=>{$('#mcp-config').textContent=JSON.stringify(await request('/api/mcp-config?profile='+$('#mcp-profile').value),null,2);$('#connect-dialog').showModal();});$('#copy-config').onclick=async()=>{try{await navigator.clipboard.writeText($('#mcp-config').textContent);toast('MCP configuration copied');}catch{toast('Select and copy the configuration text.');}};
let last=performance.now();function animate(now){const dt=Math.min(.08,(now-last)/1000);last=now;if(state.playing&&state.clip&&!document.hidden){const next=state.time+dt*+$('#playback-speed').value;if(state.clip.playback?.loop===false||state.clip.backend==='motion_capture'){state.time=Math.min(next,state.clip.duration);if(next>=state.clip.duration){state.playing=false;$('#play').textContent='▶';$('#play').setAttribute('aria-label','Play');}}else state.time=next%state.clip.duration;updateFrame();}viewer?.render();requestAnimationFrame(animate);}requestAnimationFrame(animate);
document.addEventListener('keydown',e=>{if(e.code==='Space'&&!['INPUT','TEXTAREA','SELECT','BUTTON'].includes(e.target.tagName)&&!$('dialog[open]')){e.preventDefault();$('#play').click();}});
async function boot(){try{state.capabilities=await request('/api/status');$('#footer-version').textContent='ANIMA / '+state.capabilities.version;state.tools=(await request('/api/tools')).tools;for(const tool of state.tools){const o=document.createElement('option');o.value=tool.name;o.textContent=tool.name;$('#tool-select').append(o);}$('#connection').textContent='Local engine';$('#physics-status').textContent=state.capabilities.backends.mujoco?'MuJoCo ready · 240 Hz simulation':'Install physics extras to enable MuJoCo.';await refresh();const human=state.assets.characters.find(c=>c.species==='human')||state.assets.characters[0];if(human)useCharacter(human);const initial=state.assets.clips.find(c=>c.species==='human'&&c.action==='walk')||state.assets.clips[0];if(initial)await loadClip(initial.id);busy(false);window.animaReady=true;}catch(e){$('#connection').textContent='Engine unavailable';toast(e.message,true);}}
async function buildToolForm(tool){
 const token=++toolFormSequence;$('#run-tool').disabled=true;
 try{const [recipes,body]=await Promise.all([call('list_motion_recipes',{}),state.character?.species==='human'?call('describe_body_controls',{character_id:state.character.id}):Promise.resolve({controls:{}})]);
 if(token!==toolFormSequence)return;
 toolFormContext={...state.assets,recipes:recipes.recipes,joints:state.character?.joints,coordinates:body.controls};
 toolForm=schemaForm($('#tool-form'),tool.inputSchema,toolArgs(tool.name),toolFormContext);
 $('#tool-json-mode').checked=false;$('#tool-form').hidden=false;$('#tool-args').hidden=true;
 }catch(e){toast(e.message,true);}finally{if(token===toolFormSequence)$('#run-tool').disabled=false;}
}
$('#tool-json-mode').onchange=()=>{if($('#tool-json-mode').checked){try{$('#tool-args').value=JSON.stringify(toolForm.value(),null,2);}catch(e){toast(e.message,true);}}else{try{const tool=state.tools.find(t=>t.name===$('#tool-select').value);toolForm=schemaForm($('#tool-form'),tool.inputSchema,JSON.parse($('#tool-args').value),toolFormContext);}catch(e){toast(e.message,true);$('#tool-json-mode').checked=true;}}$('#tool-form').hidden=$('#tool-json-mode').checked;$('#tool-args').hidden=!$('#tool-json-mode').checked;};
$('#mcp-profile').onchange=async()=>{$('#mcp-config').textContent=JSON.stringify(await request('/api/mcp-config?profile='+$('#mcp-profile').value),null,2);};
installBodyPanel({call,current:()=>state,refresh,loadClip,toast});
boot();
